version: "3.7"

services:

  db:
    image: postgres:13.4
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql
    networks:
      main:
        aliases:
          - database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

  cases_service:
    build: ./graphql-cases-service
    image: cases_service:latest
    networks:
      main:
        aliases:
          - cases

  users_service:
    depends_on:
      - db
    build: ./graphql-users-service
    image: users_service:latest
    networks:
      main:
        aliases:
          - users
    environment:
      DB_URL: "postgresql://admin:secret@database:5432/users"

  api_gateway:
    depends_on:
      - cases_service
      - users_service
    build: ./graphql-gateway
    image: api_gateway:latest
    ports:
      - 4000:4000
    networks:
      main:
        aliases:
          - gateway
    environment:
      USERS_API_ENDPOINT: "users:4001"
      CASES_BACKEND_API_ENDPOINT: "cases:4002"
      CASES_SUBGRAPH_API_ENDPOINT: "api.studio.thegraph.com/query/290/observatory-of-job-insecurity/v0.0.37"

networks:
  main:
