version: "3.7"

services:
  cases_service:
    build: ./graphql-cases-service
    image: cases_service:latest
    networks:
      main:
        aliases:
          - cases

  api_gateway:
    depends_on:
      - cases_service
    build: ./graphql-gateway
    image: api_gateway:latest
    ports:
      - 4000:4000
    networks:
      main:
        aliases:
          - gateway
    environment:
      CASES_BACKEND_API_ENDPOINT: "cases:4002"
      CASES_SUBGRAPH_API_ENDPOINT: "api.studio.thegraph.com/query/290/observatory-of-job-insecurity/v0.0.30"

networks:
  main:
